apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: &name azstor-prereq
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - image: docker.io/ramants17/azstor-prereq-linux:latest
        imagePullPolicy: Always
        name: *name
        args: ["azstor-prereq"]
        resources:
          requests: {}
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - name: actions
          mountPath: "/opt/actions"
        - name: hostmount
          mountPath: "/mnt/actions"
        - name: var
          mountPath: "/var"
      volumes:
      - name: hostmount
        hostPath:
          path: /opt/actions
          type: DirectoryOrCreate
      - name: actions
        configMap:
          name: nsenter-actions
      - name: var
        hostPath:
          path: /var
          type: Directory          
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nsenter-actions
  labels:
    app: nsenter
data:
  azstor-prereq: |
    #!/usr/bin/env bash
    set -euo pipefail
    modprobe -a nvmet nvme-rdma nvme-fc nvmet-fc nvme-tcp nvmet-tcp nvme-fabrics
    FILE=/var/run/azure-prereq
    NOACTIONFILE=/var/run/azure-prereq-no-action
    if [ -f "$FILE" ]; then
      echo "$FILE exists." > $NOACTIONFILE
    else
      mkdir -p /mnt/huge
      mount -t hugetlbfs nodev /mnt/huge
      echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
      echo 'vm.nr_hugepages=1024' > /etc/sysctl.d/99-hugepages.conf
      echo EOF > $FILE
      sysctl --system
      systemctl restart kubelet
    fi
    sleep infinity
---