apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hugepage
spec:
  selector:
    matchLabels:
      name: hugepage-container
  template:
    metadata:
      labels:
        name: hugepage-container
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh","-c"]
        args: ["mkdir -p host/mnt/huge; mount -t hugetlbfs nodev host/mnt/huge; echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages; echo 'vm.nr_hugepages=1024' >> host/etc/sysctl.conf; echo EOF > /var/run/reboot-required; while true; do echo Polling; sleep 1m; done"]
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        stdin: true
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root-volume
          mountPath: /host
          readOnly: false
      volumes:
      - name: host-root-volume
        hostPath:
          path: /
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
